In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("titanic_train.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
df[df['Embarked'].isnull()]
df['Embarked'] = df['Embarked'].fillna('S')

In [4]:
df[(df['Pclass'] == 1) & (df['Sex'] == 'female') & (df["Survived"] == 0)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
177,178,0,1,"Isham, Miss. Ann Elizabeth",female,50.0,0,0,PC 17595,28.7125,C49,C
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.5500,C22 C26,S
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S

In [5]:
print(df[(df['Pclass'] == 1) & (df['Sex'] == 'male')]["Age"].mean())
print(df[(df['Pclass'] == 2) & (df['Sex'] == 'male')]["Age"].mean())
print(df[(df['Pclass'] == 3) & (df['Sex'] == 'male')]["Age"].mean())
print(df[(df['Pclass'] == 1) & (df['Sex'] == 'female')]["Age"].mean())
print(df[(df['Pclass'] == 2) & (df['Sex'] == 'female')]["Age"].mean())
print(df[(df['Pclass'] == 3) & (df['Sex'] == 'female')]["Age"].mean())

41.28138613861386
30.74070707070707
26.507588932806325
34.61176470588235
28.722972972972972
21.75

In [6]:
df["Age1"] = df["Age"]
df.loc[(df["Age1"].isnull()) & (df["Pclass"] == 1) & (df["Sex"] == "male"), "Age1"] = 41.28138613861386
df.loc[(df["Age1"].isnull()) & (df["Pclass"] == 2) & (df["Sex"] == "male"), "Age1"] = 30.74070707070707
df.loc[(df["Age1"].isnull()) & (df["Pclass"] == 3) & (df["Sex"] == "male"), "Age1"] = 26.507588932806325

df.loc[(df["Age1"].isnull()) & (df["Pclass"] == 1) & (df["Sex"] == "female"), "Age1"] = 41.28138613861386
df.loc[(df["Age1"].isnull()) & (df["Pclass"] == 2) & (df["Sex"] == "female"), "Age1"] = 30.74070707070707
df.loc[(df["Age1"].isnull()) & (df["Pclass"] == 3) & (df["Sex"] == "female"), "Age1"] = 26.507588932806325

df["Age"] = df["Age1"]

df = df.drop('Age1', axis=1)
df = df.drop('Cabin', axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

In [7]:
df.loc[df["Sex"] == "male", "Sex"] = 0
df.loc[df["Sex"] == "female", "Sex"] = 1

df.loc[df["Age"] <= 22, "Age"] = 0
df.loc[(df["Age"] > 22) & (df["Age"] <= 27), "Age"] = 1
df.loc[(df["Age"] > 27) & (df["Age"] <= 37), "Age"] = 2
df.loc[(df["Age"] > 37) & (df["Age"] <= 80), "Age"] = 3

In [8]:
df["Age"].value_counts()

Age
1.0    242
0.0    231
3.0    218
2.0    200
Name: count, dtype: int64

In [9]:
df["Age"] = df["Age"].apply(lambda x: int(x))

In [10]:
df1 = df.drop(["Name", "SibSp", "Parch", "Ticket" ,"Fare", "Embarked", "PassengerId"], axis=1)
print(df1)

     Survived  Pclass Sex  Age
0           0       3   0    0
1           1       1   1    3
2           1       3   1    1
3           1       1   1    2
4           0       3   0    2
..        ...     ...  ..  ...
886         0       2   0    1
887         1       1   1    0
888         0       3   1    1
889         1       1   0    1
890         0       3   0    2

[891 rows x 4 columns]

In [11]:
X = df1.drop("Survived", axis=1)
X

     Pclass Sex  Age
0         3   0    0
1         1   1    3
2         3   1    1
3         1   1    2
4         3   0    2
..      ...  ..  ...
886       2   0    1
887       1   1    0
888       3   1    1
889       1   0    1
890       3   0    2

[891 rows x 3 columns]

In [12]:
Y = df1["Survived"]
Y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split
Xtrain, Xtest, Ytrain, Ytest = train_test_split(X,Y, test_size=0.2, random_state=101)

In [14]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(Xtrain, Ytrain)
Ypred = lr.predict(Xtest)
Ypred

array([0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0])

In [15]:
correct_count = 0
incorrect_count = 0
for i in range(179):
    if list(Ytest)[i] == Ypred[i]:
        correct_count += 1 
    else:
        incorrect_count += 1

In [16]:
from sklearn.metrics import accuracy_score, confusion_matrix
pclass = 1
sex = 1
age = 0
lr.predict([[pclass, sex, age]])[0]

c:\Users\QuentinShengYunWONG\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

np.int64(1)